name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cssDiff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: curl https://www.projectwallace.com/webhooks/v1/imports/preview?token=6f92d25c-1f52-4335-86ea-1240425dd26a -X POST -H "Content-Type: text/css" -d @style.css
        with:
          project-wallace-token: ${{ secrets.PROJECT_WALLACE_TOKEN }}
